### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by jvbussel** [aws-quickstart/quickstart-linux-bastion#10]
When the 2nd user tries to use th bastion he get the message:

script: cannot open /tmp/messages: Permission denied

the /tmp/messages file is created for the user/group of the first user.

**Comment by alexander-zimmermann** [comment]
Encounter the same problem

**Comment by jvbussel** [comment]
Hi Alexander,

In:

/etc/ssh/sshd_config

you will find (almost at the end):

ForceCommand /usr/bin/bastion/shell

It is the shell script which is causing the issue. I altered it to suit my
own needs. In this case it allows only the ec2-user to logon and go to the
prompt. All other users do need to supply the command for the sers to jump
to.
Below my implementation of the script.


#!/bin/bash
#set -x
bastion_mnt="/var/log/bastion"
bastion_log="bastion.log"

whoami="`whoami`"
date="`date "+%Y-%m-%d %H:%M:%S"`"

# Log connection
echo "$whoami:$date:$SSH_ORIGINAL_COMMAND" >>
"${bastion_mnt}/${bastion_log}"

if [ "$whoami" == "ec2-user" ]; then
    if [ -z "$SSH_ORIGINAL_COMMAND" ]; then
        /bin/bash
        exit 0
    else
        $SSH_ORIGINAL_COMMAND
    fi
else
    if [[ "$SSH_ORIGINAL_COMMAND" =~ ^"ssh" ]]; then
        $SSH_ORIGINAL_COMMAND
    else
        echo "This bastion does NOT support interactive sessions. Please
specify a ssh command for the server to jump to"
        exit 1
    fi
fi



Regards,

Joop

**Comment by agamzn** [comment]
This should be resolved by now. However I need to spin up an instance and verify before closing.

**Comment by agamzn** [comment]
Able to reproduce. The use-case here is multiple accounts on the bastion. Said accounts are created after the bastion is launched.

**Comment by agamzn** [comment]
Closing this in favor of #32. Duplicate.
