### ISSUE TITLE
BastionAutoScalingGroup - The requested configuration is currently not supported. 

### ISSUE THREAD

**Issue by snipergotya** [aws-quickstart/quickstart-linux-bastion#104]
I get the following error when i run this template:

The requested configuration is currently not supported. Please check the documentation for supported configurations. Launching EC2 instance failed.
--

Any ideas what might be wrong?

**Comment by snipergotya** [comment]
I was running this in EU-North-1 & it was failing.

Tried it in US-East-1 and it worked fine with the exact same settings.

So I'm assuming its something to do with eu-north-1 region

**Comment by nunnsby** [comment]
I have submitted pulls for issues #105 and #106 due to t2.* not being supported in that region, as per your reddit post: https://www.reddit.com/r/aws/comments/j2070k/awsquickstart_bastion_host_failing_to_create/.
You can confirm in the AWS Console and also on : https://ec2instances.info/
