### ISSUE TITLE
Why is there no /var/log/bastion/bastion.log file

### ISSUE THREAD

**Issue by FFTU** [aws-quickstart/quickstart-linux-bastion#108]
I follow the tutorial configuration in https://docs.aws.amazon.com/quickstart/latest/linux-bastion/welcome.html, but there is no log file；no /var/log/bastion/bastion.log    and Linux-bastion-BastionMainLogGroup log stream is empty
ec2 Amazon Linux（amzn2-ami-hvm-2.0.20200722.0-x86_64-gp2）

thanks

**Comment by msm46** [comment]
https://github.com/aws-quickstart/quickstart-linux-bastion/commit/5472050a5315b9e3a8d97d60ba402479326af4e5

Log file output destination changed
`` ```
/var/log/bastion/bastion.log ⇒ /var/log/auditd/auditd.log
`` ```

However, the logs have not been transferred to CloudWatch ...
Linux-bastion-BastionMainLogGroup log stream is empty ...
why?

**Comment by msm46** [comment]
Because there is an error in the file path of the transfer settings
Not transferred to CloudWatch

```
Wrong: /var/log/auditd/auditd.log
Correct: /var/log/audit/audit.log
```

```
■quickstart-linux-bastion/scripts/bastion_bootstrap.sh
Line：123 ～ 142

    cat <<EOF >> /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
{
    "logs": {
        "force_flush_interval": 5,
        "logs_collected": {
            "files": {
                "collect_list": [
                    {
                        "file_path": "/var/log/auditd/auditd.log",  ★「/var/log/audit/audit.log」 is correct
                        "log_group_name": "${CWG}",
                        "log_stream_name": "{instance_id}",
                        "timestamp_format": "%Y-%m-%d %H:%M:%S",
                        "timezone": "UTC"
                    }
                ]
            }
        }
    }
}
EOF
```

**Comment by Sam-Hoult** [comment]
Here facing the same issue, this is a problem when trying to audit logs, which is one of the main reasons we implemented a bastion.

**Comment by Moandh81** [comment]
Hi, 

In which file or directory do I find the configuration of bastion.log file please ? 
I can't find it.
