### ISSUE TITLE
AuditD does not record SSH client IP & Documentation log mismatch

### ISSUE THREAD

**Issue by dhananjaipai** [aws-quickstart/quickstart-linux-bastion#125]
The documentation page https://aws-quickstart.github.io/quickstart-linux-bastion/ shows the bastion.log file to have the time, the from IP, the user, the pwd, and the command all in a neat log line.

The current implementation with auditd however logs everything in multiple lines with separate type=CWD type=EXECVE etc.. It also does not log the IP of the connected user (that was earlier logged with who am i --ips)

I think the quickstart documentation is a bit misleading (outdated?) and the logs are not captured in the same format as shown and without the IP address. Kindly update the documentation to show the current log level and format?

Also, is there any work-around to extract data from auditd to the previous format and stream to cloudwatch logs?

**Comment by roycncn** [comment]
I think due to the bashrc is under user's control. They decided to change the approach logging the command. If you really want to back to the way that showed in the Quick-Start. Please check this branch: https://github.com/aws-quickstart/quickstart-linux-bastion/tree/tonyv-main-aug-10-2020
