### ISSUE TITLE
It would be good to make the secondary subnet optional 

### ISSUE THREAD

**Issue by quickzebra** [aws-quickstart/quickstart-linux-bastion#136]
it will get error "Template error: Subnet doesn't exist. Rollback requested by user."

Understood it's for resiliency to have a second bastion host in 2nd AZ.   It would be good to provide options.  Alternatively please make this field mandatary.   Thanks.

**Comment by davmayd** [comment]
I'm not sure I follow. The `PublicSubnet2ID` parameter is of type 'AWS::EC2::Subnet::Id', meaning you have to select a value from a dropdown in the CloudFormation console, making it mandatory.

**Comment by supergibbs** [comment]
Even if you only deploy one bastion, it's good to specify two AZs so if an AZ goes down the ASG can deploy to an alternate. Doesn't add cost and unlikely you have a VPC with only one AZ.
