### ISSUE TITLE
Bastion Host Initialization and Script Abort on Stack Updates 

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-linux-bastion#150]
When an EKS stack is updated, the cfn-signal fails which fails the script. Since stack updates should be supported, the bootstrap script should recognize the status of "UPDATE_COMPLETE" as a non-error condition - potentially simply not call cfn-signal at all.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/11597190/167416697-1599e372-afea-46ff-a496-2905adb4784a.png)

**Comment by tlindsay42** [comment]
@DarwinJS Sorry for the delay. Pretty sure that I fixed this at some point this year and can no longer duplicate. Please re-open with additional troubleshooting details if needed.

![image](https://user-images.githubusercontent.com/11078689/206050414-995616ac-6a7f-4757-8454-41aa8a09a91d.png)
