### ISSUE TITLE
'BastionBootstrapScript' is failing with initial deployment, but works when done as stack update

### ISSUE THREAD

**Issue by DarwinJS** [aws-quickstart/quickstart-linux-bastion#152]
With the exact same [custom bastion script](https://gl-public-templates.s3.amazonaws.com/eksbastionbootstrap/bootstrap.sh), I am getting the below error when trying to stand it up with the current EKS QuickStart.

You can see in the script I simple add ssm-user to sudoers and install docker.

However, with an older one I was able to add the script to advanced parameters, rerun the stack and it works fine.

![Screen Shot 2022-05-07 at 9 46 43 AM](https://user-images.githubusercontent.com/11597190/167257110-b28ee992-f901-4dc0-bc76-636b428a4bbd.png)

**Comment by DarwinJS** [comment]
I just re-re-tested this to be sure that this is what I am seeing and it is indeed confirmed. Fails if used with initial stack deployment, works if you update the advanced deployment stack followed by updating the eks stack.

**Comment by tlindsay42** [comment]
Fixed this at some point this year and no longer able to reproduce.
