### ISSUE TITLE
not able to change the bucket name specified in the template

### ISSUE THREAD

**Issue by ritwik-singh-yash** [aws-quickstart/quickstart-linux-bastion#20]
on changing the bucket name in the template, the stack launch fails with the error message 
"Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement".
I have also tried changing each and every field related to the  bucket(IAM policy, refernces etc) but it does not seem to work.
according to the logs the command which runs the bastion_bootstrap script fails each time and i have no idea why.
[cfn-init.log](https://github.com/aws-quickstart/quickstart-linux-bastion/files/1611484/cfn-init.log)

**Comment by santiagocardenas** [comment]
Make sure that the bucket you created is in a region that supports AWS API Signature Version 2. 

These are regions that are _**not**_ in the list here: https://docs.aws.amazon.com/general/latest/gr/signature-version-2.html

The reason for this, is that there is a limitation with cfn-init and downloading files from virtual hosted-style URLs.

**Comment by santiagocardenas** [comment]
Btw, it seems though that my note above isn't affecting your use case.

To confirm, do you see the file at /tmp/bastion_bootstrap.sh and are the contents of that file the actual bootstrap script?

**Comment by santiagocardenas** [comment]
Also, what happens if you try launching from the `quickstart-reference` bucket as the value of Quick Start S3 Bucket Name (QSS3BucketName)?

**Comment by ritwik-singh-yash** [comment]
I am launching my stack in North Virginia region.
The bastion_bootstrap.sh is being copied in the tmp folder and has the actual content.
When I use the actual template with quickstart buckets it works fine, which baffles me more.

**Comment by ritwik-singh-yash** [comment]
I have a question. The bucket from where i am pulling the bastion_bootstrap.sh gives does not give me the file link which is formed in the template i.e.
"https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}/bastion_bootstrap.sh",
It is like : https://s3.amazonaws.com/${QSS3BucketName}/${QSS3KeyPrefix}/bastion_bootstrap.sh.
Does this make any difference?
Although testing with the actual link also gives me the same error.

**Comment by santiagocardenas** [comment]
This is interesting. I've tried it with every Linux OS supported in the Quick Start and it deploys as expected. When copying, did you make any modifications? What Linux OS were you using?

From the log you attached, it seems that the issue happens when executing the bootstrap script command, as seen by the following line:
`2018-01-08 11:29:16,605 [DEBUG] Command b-bootstrap output: /bin/sh: ./tmp/bastion_bootstrap.sh: No such file or directory`

**Comment by santiagocardenas** [comment]
In regard to the difference is URL, it's just virtual hosted-style vs. path-style S3 URLs. You can see more info here: https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

The advantage of using virtual hosted-style is that you can use a single s3.amazonaws.com URL for any bucket located in any region. Path style URLs require a different S3 URL for every region and you must know that region ahead of time.

**Comment by ritwik-singh-yash** [comment]
I have actually made some change to the template but not to the script.
In the template I am trying to copy files from one of my buckets into another bucket using user data.
But there has been no change in the bootstrap file configuration.
I am using amazon linux as of now and have not tested it on any other OS.
Another thing that is bugging me that even when i try to execute that script manually it fails with a validation error. I have tried changing its permission and mode but to avail.
[gitCopy.txt](https://github.com/aws-quickstart/quickstart-linux-bastion/files/1617537/gitCopy.txt)

**Comment by santiagocardenas** [comment]
Can you run the Quick Start from the published location as is (that is, without your changes)?
This would help us narrow down if it's because of changes introduced that should be diffed.

**Comment by agamzn** [comment]
@ritwik-singh-yash Is this issue still on-going? What were your results?

**Comment by ritwik-singh-yash** [comment]
I had created some workaround for that, just for my use case but there is one potential solution from AWS which I have not tested but should work according to the AWS support team.
"In order to point the template at your own bucket, you'll need to place the file in a particular folder structure. In your bucket, create a folder called "linux", then inside this folder create another folder called "scripts". Place your copy of the bastion_bootstrap.sh file inside these folders. Your file path should then look like this: my-bucket/linux/scripts/bastion_bootstrap.sh"
As AWS quickstarts are tightly coupled these intricate details need to be taken care of.

**Comment by agamzn** [comment]
Glad to see you're operational and found a solution. The vanilla templates (in master) allow you to customize the bucket and key-prefix (linux directory in your example) via the `QSS3Bucket` and `QSS3KeyPrefix` parameters, respectfully. 

I'm leaving this open for tracking a couple action-items further up the thread.
