### ISSUE TITLE
Can you please support dedicated ec2 tenancy?

### ISSUE THREAD

**Issue by shicholas** [aws-quickstart/quickstart-linux-bastion#30]
I have a use case to use this template on dedicated hardware, can you please support       

```yaml
PlacementTenancy: 
        Ref: PlacementTenancy
```

on https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html#cfn-as-launchconfig-placementtenancy

🙏 thanks for this!

**Comment by agamzn** [comment]
Sure! I've added it to the backlog. I'm hoping to be able to allocate some time for this soon.
