### ISSUE TITLE
Bastion config does not catch all commands

### ISSUE THREAD

**Issue by ppiscuc** [aws-quickstart/quickstart-linux-bastion#31]
Hi,

FYI
Not all commands are logged using the method in these templates. For example, if a user runs the command:
```
ls; history -c
ls; history -r
```

then the command above will not be logged in /var/log/bastion/bastion.log

The above has been tested on a Centos machine, but mechanism is the same on the Amazon/Ubuntu/Centos AMIs.

Paul

**Comment by agamzn** [comment]
This has been on our radar and will be fixed in Version 2 (in active development).
