### ISSUE TITLE
Possible to consider a more immutable solution?

### ISSUE THREAD

**Issue by c-knowles** [aws-quickstart/quickstart-linux-bastion#34]
Would it be possible to consider providing AMIs which are more immutable where appropriate with less of the setup on instance init? We've seen several occurrences using this project where new bastion instances don't start correctly due to point in time failures or outside changes breaking the setup. The last occurrence, one bastion has to be replaced and some problem with the AWS CLI install caused it to not boot and attach the correct EIP. I'm assuming https://github.com/aws-quickstart/quickstart-linux-bastion/issues/15 is a similar issue.

Internally we're in the process of taking the nice work here and converting some of it into Packer, leaving things like EIP attachment etc in the init scripts. We already have some of that if it would be useful upstream. If that was provided here it could be the Packer setup run through CI or the project could provide the AMIs (in which case we'd need to consider how to rebuild when the base AMI rebuilds).

**Comment by agamzn** [comment]
Hey Chris, 

In the context of a quickstart: unfortunately not. QuickStarts by nature are dynamic builds from CloudFormation templates. With that said, you're more than welcome to use the quickstart as a base for your own (AMI) needs. 

Thanks
Andrew
