### ISSUE TITLE
The URL of submodule is in the SSH not the HTTPS version

### ISSUE THREAD

**Issue by pkaszuba** [aws-quickstart/quickstart-linux-bastion#43]
In the .gitmodules file there is URL to the aws-quickstart submodule
`url = git@github.com:aws-quickstart/quickstart-aws-vpc.git`

Both this and that repo are public, so it should be possible to pull them even without GitHub account and SSH keys. However they are not. It makes quite a big problem e.g. for working with this repo with Jenkins. Could you change the URL to
`url = https://github.com/aws-quickstart/quickstart-aws-vpc`
please?

It would make our CD process much simpler (less needless dependencies like SSH keys that have to be copied to GitHub).

**Comment by agamzn** [comment]
@pkaszuba , I thought I pushed this awhile back. This is pending CI/CD on our side. As soon as it is in master, this should close.
