### ISSUE TITLE
provide a way to pass dynamic values to AlternativeInitializationScript

### ISSUE THREAD

**Issue by jaymccon** [aws-quickstart/quickstart-linux-bastion#47]
Would be great to be able to get some key-value pairs to this script, so that bootstrapping can be tailored to a deployment. 

A stack parameter that allows a comma separated list of key=value that then get exported as environment variables, which the initialization script can consume should do the trick.

In my use case I want to pre-configure the kubernetes cli for the environment. to do this I need to create a config file with several environment specific values. With the current static file my only option is to dynamically write the values into the AlternativeInitializationScript file before executing the bastion stack, which seems like a lot more effort than necessary.

**Comment by agamzn** [comment]
I'm thinking a very explicit namespace. I have concerns around env vars being overridden and weird things happen. This is a bastion, after all.  @jaymccon , does `QS_LINUX_BASTION_ENVVAR_${KEY} = VAL` work for you

**Comment by agamzn** [comment]
Pinging @jaymccon

**Comment by agamzn** [comment]
Merged via #49
