### ISSUE TITLE
Allow passing instance profile in as a parameter

### ISSUE THREAD

**Issue by jaymccon** [aws-quickstart/quickstart-linux-bastion#48]
When using the bastion template as a submodule it would be useful to be able to define the instance profile in my stack, granting whatever permissions are needed for the particular use-case, and pass the arn to the bastion, instead of having a static role assigned as it is done today.

Alternatively, pass the role ARN back to the parent as an output, then i can attach the additional policies to the role.

**Comment by agamzn** [comment]
I'm in favor of BYO-IAM. If you want to customize the IAM permissions associated with the bastion, then I think allowing you to tell me what the ARN of the desired-policy is a good idea.

**Comment by agamzn** [comment]
Merged via #49
