### ISSUE TITLE
Logging easily circumvented

### ISSUE THREAD

**Issue by fboussarsar** [aws-quickstart/quickstart-linux-bastion#52]
The current way to force logging to bastion.log can be easily circumvented:

1. The `PROMPT_COMMAND` variable is set in `/etc/bashrc`, which is sourced by `.bashrc` in the user's home and which is under the user's control. A user can modify that file to prevent sourcing `/etc/bashrc`, logout and re-login, and escape logging. `/etc/profile.d/` would be a better place for setting this variable.

2. Even if set in `/etc/profile.d/`,  `/etc/profile` and  `/etc/profile.d/` files are only sourced if the shell is a login shell, or spawned with the `--login` option. Choosing `/etc/profile.d/` would mean adding that option to the bash spawned in the `ForceCommand` script.

3. Even if the prompt command is forced correctly upon login, it would be enough for the user to spawn a non-login bash, to avoid sourcing `/etc/profile`. The  `PROMPT_COMMAND` variable is then no longer readonly in the subshell, and can be unset. And logging is no longer performed.

I know a version 2 is being worked on currently. But are there thoughts on how to correct this?

Thank you!

**Comment by agamzn** [comment]
This is an interesting one.  For context, here's the approach I have in v2, but I don't think this solves the issue either. I'm thinking on this...

```
function configure_bash_commands_to_syslog() {
    echo "${FUNCNAME[0]} Started"

    bash_include_file="${1}"
    cat <<-EOF >> ${bash_include_file}
        PROMPT_COMMAND=$(history -a)
        typeset -r PROMPT_COMMAND

        function log2syslog
        {
           declare SSH_CONNECTING_IP
           declare command
           declare local_datetime
           command=${BASH_COMMAND}
           SSH_CONNECTING_IP=${SSH_CLIENT%% *}
           local_datetime=$(date "+%Y-%m-%d %H:%M:%S")
           logger -p local7.notice -t linux_bastion -i -- "${local_datetime}|${SSH_CONNECTING_IP}|${USER}|${PWD}|${command}"
        }
        trap log2syslog DEBUG
EOF
    echo "${FUNCNAME[0]} Started"
}
```

**Comment by fakhreddinebb90** [comment]
I have solved this (I think) by disabling shell login altogether for normal users, and configuring clients to use the bastion as an SSH Proxy. (Possible on linux via `ProxyCommand='ssh -W %h:%p user@bastion'` and also on Putty)

As for logging commands supplied as a ssh argument, I enabled auditd.

**Comment by agamzn** [comment]
@fakhreddinebb90  - any special arguments in auditd? Always happy to consider my approach to not be the best. :)

**Comment by fakhreddinebb90** [comment]
Well I don't know if mine is the best either. 
Looking back, I only enabled command logging for admins.
I included this in my bootstrap script. However, the logs are ugly to look at. I only had a day left to finish the thing by the time I opened this issue and it's still not in prod yet. I included this in ` /etc/audit/rules.d/audit.rules`

# Log all commands by root and ec2-user 
-a exit,always -F arch=b64 -F euid=0 -S execve 
-a exit,always -F arch=b32 -F euid=0 -S execve 
-a exit,always -F arch=b64 -F euid=1000 -S execve 
-a exit,always -F arch=b32 -F euid=1000 -S execve `

**Comment by avattathil** [comment]
@andrew-glenn thoughts on this enhancement (candidate for version2.1 ?)
