### ISSUE TITLE
Stockholm region: Whichever BastionAMIOS we use, we always get an error

### ISSUE THREAD

**Issue by astoykovych** [aws-quickstart/quickstart-linux-bastion#63]
Whichever BastionAMIOS we use on Stockholm region, we always get an error:

Template error: Unable to get mapping for AWSAMIRegionMap::eu-north-1::AMZNLINUXHVM

Template error: Unable to get mapping for AWSAMIRegionMap::eu-north-1::CENTOS7HVM

Template error: Unable to get mapping for AWSAMIRegionMap::eu-north-1::US1604HVM

Template error: Unable to get mapping for AWSAMIRegionMap::eu-north-1::US1404HVM

**Comment by astoykovych** [comment]
Did anybody face this problem, and how can we overcome it?

**Comment by andrew-glenn** [comment]
@astoykovych  - you were seeing this because the template didn't support eu-north-1. I've added the AMI IDs to the template. As soon as you see the commit in master you should be good to go.

**Comment by astoykovych** [comment]
Thank you!
