### ISSUE TITLE
Override LinuxBastion as name of host

### ISSUE THREAD

**Issue by techcto** [aws-quickstart/quickstart-linux-bastion#67]
Is it possible override LinuxBastion as the name of the host to better match parent stack names?

**Comment by andrew-glenn** [comment]
@techcto  - Would you prefer an auto-generated name (Inherited from the parent stack), or a user-provided name?  I'm thinking you desire an auto-generated name

**Comment by techcto** [comment]
Ugg. Hard one.  Originally I agree that it should match stack name, but using the EKS Quickstart, I wished it matched the names of the EKS Worker nodes.

**Comment by andrew-glenn** [comment]
@techcto - OK. Then "user-provided" value. It defaults to 'linux-bastion', but we can override it upstream in the EKS quickstart. (As a param)

**Comment by tbulding** [comment]
I added a parameter for Bastion Host Name.

**Comment by tbulding** [comment]
Reopening till we merge into master

**Comment by techcto** [comment]
I see this has been added.  Thank you. At present it is hard-coded to EKSBastion, I am going to recommend changing that to something like: 
`!Join ["-", [ 'EKS', !GetAtt EKSControlPlane.Outputs.EKSName, 'Bastion' ]]`
This way it sorts nice in the instance list.  I am testing this now.
