### ISSUE TITLE
Support for Amazon Linux 2

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-linux-bastion#68]
Support to deploy with Amazon Linux 2 AMI.

**Comment by tomiszili** [comment]
Hello @knoxilla 

To be honest i'm not developing a generic solution for this problem, because i'm not patient enough to add this feature. I copy the existing template and deleted/changed all those sections i don't want to use for amazonlinux2.

I had this problem for so long, so the script under Userdata should be debugged line by line on an EC2 with empty amzlinux2.
As far as i remember the first issue is with the yum can't install the epel-release, because you first have to run some costum command, which the `yum install -y epel-release` will return.
But I realised that you don't have to install the epel-release, you can simply run `yum install -y python2-pip` if you want pip2, but you have natively installed pip3 and awscli on amazonlinux2.

So if you want to use amazonlinux2 only, you should rewrite the userdata of the template.
Change all these lines: https://github.com/aws-quickstart/quickstart-linux-bastion/blob/master/templates/linux-bastion.template#L568-L585 to 
'pip3 install awscli --upgrade`

**Comment by knoxilla** [comment]
Thanks much.   I will give it a go - thanks for the pointers and recap of things you'ave already figured out.   Cheers,

-t

**Comment by timtubescience** [comment]
+1 I am trying to get psql client v10 installed, to connect to a PSQL 10 RDS instance.  It should be wicked easy to get 10 installed on amazon linux 2, and I fear staying on the older version of amazon linux as support already seems to be dwindling.

**Comment by avattathil** [comment]
depend on https://github.com/aws-quickstart/quickstart-linux-bastion/pull/80

**Comment by avattathil** [comment]
Added in https://github.com/aws-quickstart/quickstart-linux-bastion/blob/34ffdce06be6cdf3bd4734717571927f763a1c49/templates/linux-bastion.template#L241-L379
