### ISSUE TITLE
Bastion not updatating after CFN parameter modification.

### ISSUE THREAD

**Issue by tomiszili** [aws-quickstart/quickstart-linux-bastion#69]
If the launchconfiguration parameters modifies, the old bastion host shloud be deatach EIP and be terminated. After the termination the autoscaling group with the new launch config should initialize a new bastion host with the new parameters.
Please add this support to the template.

**Comment by avattathil** [comment]
@tbulding please look into this and update the issue with plans

**Comment by tbulding** [comment]
I modified the ASG. to replace the ASG on updates.

**Comment by tbulding** [comment]
Reopening till we merge into master
