### ISSUE TITLE
Can Linux Bastion setup be replaced by AWS Client VPN?

### ISSUE THREAD

**Issue by arjanschaaf** [aws-quickstart/quickstart-linux-bastion#84]
I'm interested in using the EKS quickstart as a starting point for a new EKS deployment. While the Bastion setup is really cool, I was wondering: would the newer AWS Client VPN SaaS offering be a valid replacement? https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/what-is.html
It would make these kind of deployments even less complex than they already are :-)

**Comment by tlindsay42** [comment]
Sorry for our very delayed response, but yes- AWS Client VPN is a viable alternative.
