### ISSUE TITLE
AllowTcpForwarding is not enabled when specifying the parameter in the template

### ISSUE THREAD

**Issue by JemaaWassim** [aws-quickstart/quickstart-linux-bastion#86]
cfn-init.log shows that the parameters was passed with no issues [1], however, the /etc/ssh/sshd_config file is not updating the value of "TCP_FORWARDING" to be considered (It is kept as Yes, but by default it is commented). A workaround was to append the value through the userdata manually.

===========
cfn-init.log
===========

[INFO] Installing banner ... 
Value of TCP_FORWARDING - true
Value of X11_FORWARDING - true
setup_os Started
setup_os Ended
setup_logs Started
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 58.3M  100 58.3M    0     0  91.1M      0 --:--:-- --:--:-- --:--:-- 91.0M
create group cwagent, result: 0
create user cwagent, result: 0
Created symlink from /etc/systemd/system/multi-user.target.wants/amazon-cloudwatch-agent.service to /etc/systemd/system/amazon-cloudwatch-agent.service.
prevent_process_snooping Ended
Querying the assigned public IP
Determining EIP Association Status for [<?xml]
Determining EIP Association Status for [34.192.111.204]
Elastic IP [34.192.111.204] already has an association. Moving on.
Determining EIP Association Status for [54.210.64.20]
Elastic IP [54.210.64.20] already has an association. Moving on.
Detected a NULL Value, moving on.
Detected a NULL Value, moving on.
request_eip Ended
Bootstrap complete.

===========
 /etc/ssh/sshd_config
===========
#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
X11Forwarding yes

[1] https://github.com/aws-quickstart/quickstart-linux-bastion/blob/e51629f713324d24eda0255424d9a2fab8d36209/scripts/bastion_bootstrap.sh#L440

**Comment by tlindsay42** [comment]
Working in the current build, so this was solved at some point.
