### ISSUE TITLE
Failed to retrieve bastion_bootstrap.sh

### ISSUE THREAD

**Issue by mkamthe-xl** [aws-quickstart/quickstart-linux-bastion#87]
We are using aws-quickstart/quickstart-linux-bastion repository to deploy bastion host. The bastion host deployment fails as cfn-init script is not able to access bastion_bootstrap.sh from s3 bucket. It looks like signature version not being compatible is the root cause of the problem. PFA cfn-init.log
[cfn-init.log](https://github.com/aws-quickstart/quickstart-linux-bastion/files/4454719/cfn-init.log)

We observed in cfn-init.log that Signature Version 2  is used as no region was specified in S3 URL. It looks like issue occurred due to signature version incompatibility.

We are deploying cloud formation stack using taskcat with QSS3BucketName: $[taskcat_autobucket]

**Comment by jonlprice** [comment]
We are seeing the same issue with aws-quickstart/quickstart-linux-bastion, in an account that was previously working ok

Here's the error from cloud-init-output.log:

Error occurred during build: Failed to retrieve https://aws-quickstart-us-east-1.s3.us-east-1.amazonaws.com/quickstart-linux-bastion/scripts/bastion_bootstrap.sh: HTTP Error 403 :<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>36DAB2C0060F7A27</RequestId><HostId>yCXVSe3swEBFpTdUy9DUJr+QIKYOYub0ip4fyLGTZ7NC0/A7jOGSb/TslgCsDXzKYBeIZIzZAJQ=</HostId></Error>

Once the bastion is up running the following works ok:
curl -O https://aws-quickstart-us-east-1.s3.us-east-1.amazonaws.com/quickstart-linux-bastion/scripts/bastion_bootstrap.sh

As this is the last command before cfn-signal in the stack not sure how any other ACL rules can have been applied to make this outbound access work ok

**Comment by martin-niklasson** [comment]
I had the same problem. I found a workaround, which may be helpful to other AWS newbies, like me. 

Clone the github repository for this Guide:
git clone --recursive https://github.com/aws-quickstart/quickstart-linux-bastion.git

Make an Amzon S3 bucket in the Management Console. It can be private (default settings). Remember which region your bucket is in. 

Drag and drop the entire "quickstart-linux-bastion" directory you got from git into the bucket. 

Run the Guide and change the S3 bucket name and region to your own bucket.

**Comment by tlindsay42** [comment]
Resolved in #176
