### ISSUE TITLE
Setup_Log() is using old style S3 urls

### ISSUE THREAD

**Issue by git-craker** [aws-quickstart/quickstart-linux-bastion#92]
Hi, 

Refer line in setup_logs() function : 
curl "https://amazoncloudwatch-agent-${REGION}.s3.${REGION}.${URL_SUFFIX}/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm"   

In sydney region this results in error and I am sure it will error out in other regions.
**curl: (6) Could not resolve host: amazoncloudwatch-agent-ap-southeast-2.s3.ap-southeast-2**

New URL in Sydney will be  **curl https://s3.ap-southeast-2.amazonaws.com/amazoncloudwatch-agent-ap-southeast-2/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm**

So in the script it should be : 
**curl 
https://s3.${REGION}/amazoncloudwatch-agent-${REGION}/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm"**

**Comment by tlindsay42** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access

> Currently, Amazon S3 supports both virtual-hosted–style and path-style URL access in all AWS Regions. However, path-style URLs will be discontinued in the future.
